version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the pre_build phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Test started on `date`
      - echo `pwd`
      - echo `ls -l`
      - echo `cat /etc/passwd`
      - echo Test completed on `date`
  post_build:
    commands:
      - echo Nothing to do in the pre_build phase...

